### ISSUE TITLE
API for exporting data

### ISSUE THREAD

**Issue by dclobato** [tomsoft1/OpenSensor#1]
Hi,

How about an API call for export data from one sensor? :)

I was thinking on something like:

```
<HOST>/sensor/<SENSOR_ID>/measures?start=<initial_timestamp>&end=<final_timestamp>
```

Cheers

**Comment by tomsoft1** [comment]
This exists already, in JSON format, it was just not documented yet.

See now the doc: https://github.com/tomsoft1/OpenSensor/wiki/API

The format is the following:

 http://api.opensensorcloud.com/sensor/'SENSOR_ID'/measures

And it will return the results in json format
Let me know if it's fine for you, or if you would like another format.

I'll add paging and ranging extra parameter to reduce the volume of data returned

**Comment by dclobato** [comment]
Super! :)
